### ISSUE TITLE
Renaming subfolders of `LabWork - Assignments` folder

### ISSUE THREAD

**Issue by Aamir-Ansari-almost** [Aamir-Ansari-VESIT/Sem-3#1]
Rename the folders inside `LabWork - Assignments/<all folders>/`.
eg. `Sem-3/LabWork - Assignments/DSA/Experiment 01`
Change the name of `Experiment 01` folder name
New names should be in the following format,
`<topic of files inside the folder> <(Experiment number)>`

**Comment by cyrilckurian** [comment]
I would like to work on this, can you assign me? @Aamir-Ansari-almost
