### ISSUE TITLE
Restructure subdirectories of `LabWork - Assignments/DSA/` 

### ISSUE THREAD

**Issue by Aamir-Ansari-almost** [Aamir-Ansari-VESIT/Sem-3#2]
Currently inside `LabWork - Assignments/DSA/` directory, all the code is written in C.
current folder structure is:
`Code`  (original code in C)
`Outputs` 
`Write-up`

Create a folder in the same directory for java and C++ code.
Additionally create empty .java and .cpp file for future use

## Create the following folders
`java-code` (add .java file)
`cpp-code` (add .cpp file)

**Comment by Gowrishankar04** [comment]
Hi @Aamir-Ansari-almost ,

Can you please assign this to me?

Thanks
